# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0012_auto_20161206_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Art', 'Art'), ('Food', 'Food'), ('Music', 'Music'), ('Shopping', 'Shopping'), ('Theatre', 'Theatre')], default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Null', max_length=20),
        ),
    ]
