# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0013_auto_20161206_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidevent',
            name='event_bms',
            field=models.CharField(default=b' ', max_length=200),
        ),
    ]
