# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0015_auto_20161210_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=b'default.png', upload_to=b'/static/yellow_line/event_images'),
        ),
    ]
