# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0017_auto_20161210_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[(b'Art', b'Art'), (b'Food', b'Food'), (b'Music', b'Music'), (b'Shopping', b'Shopping'), (b'Theatre', b'Theatre')], default=b'Null', help_text=b'Please choose what category the event falls under.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text=b'Please choose the date of the event.', verbose_name=b'event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text=b'Please upload an image for the event.', upload_to=b'/static/yellow_line/event_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_metro',
            field=models.CharField(blank=True, help_text=b'Please enter the name of the nearest metro station', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text=b'Please enter name of the event and make sure it begins with a capital letter', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_paid',
            field=models.CharField(choices=[(b'Paid', b'Paid'), (b'Free', b'Free')], default=b'Null', help_text=b'Please choose if the event is paid or free.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, help_text=b'Please enter the name of the venue of the event.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_website',
            field=models.CharField(blank=True, help_text=b'Please enter a link to the event website or Facebook page.', max_length=200),
        ),
    ]
