# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0019_auto_20161210_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Art', 'Art'), ('Food', 'Food'), ('Music', 'Music'), ('Shopping', 'Shopping'), ('Theatre', 'Theatre')], default='Null', help_text='Please choose what category the event falls under.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='Please choose the date of the event.', verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text='Please upload an image for the event.', upload_to='/static/yellow_line/event_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_metro',
            field=models.CharField(blank=True, help_text='Please enter the name of the nearest metro station', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text='Please enter name of the event and make sure it begins with a capital letter', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Null', help_text='Please choose if the event is paid or free.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, help_text='Please enter the name of the venue of the event.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_website',
            field=models.CharField(blank=True, help_text='Please enter a link to the event website or Facebook page.', max_length=200),
        ),
        migrations.AlterField(
            model_name='paidevent',
            name='event_bms',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
