# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yellow_line', '0021_auto_20161210_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('Art', 'Art'), ('Food', 'Food'), ('Music', 'Music'), ('Shopping', 'Shopping'), ('Theatre', 'Theatre')], default='Null', help_text='Please choose what category you like', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
