# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 01:16
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Art', 'Art'), ('Food', 'Food'), ('Music', 'Music'), ('Shopping', 'Shopping'), ('Theatre', 'Theatre')], default='Null', help_text='Please choose what categories you like', max_length=20),
        ),
    ]
