# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0023_auto_20161211_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theatre',
            field=models.BooleanField(default=False),
        ),
    ]
