# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0024_auto_20161211_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='art',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='food',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='music',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shopping',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theatre',
        ),
    ]
