# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0025_auto_20161212_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theatre',
            field=models.BooleanField(default=False),
        ),
    ]
